# 반복측정 분산 분석(AnovaRM)
반복측정 자료는 동일 개체에 대해서 시간의 흐름에 따라 여러번 측정한 결과입니다. 이렇게 측정된 데이터는 변수 상호간에는 독립적이지만, 변수내에서는 상관성을 가지고 있습니다. 이러한 자료는 별도의 대조군이 필요하지 않고 작은 차이도 알아낼수 있어 연구의 정확도를 증가시킬수 있습니다.

# 반복측정 자료의 특징

반복적으로 측정된 자료를 일반적인 **t-test, ANOVA**로 분석할 경우, 오류가 증가해 신뢰성이 줄어듬으로 주의해야 합니다. 따라서 반복측정 일반선형 모델을 사용해야 합니다.

# Repeated Measures ANOVA in Python using Statsmodels

- 출처: https://www.marsja.se/repeated-measures-anova-in-python-using-statsmodels/

## Statsmodels & Pandas 설치
`Statsmodels` 과 `Pandas`를 아래와 같이 `pip`명령어로 설치가 가능합니다.

```bash
pip install pandas statsmodels
```

## AnovaRM

`Statsmodels`의 `AnovaRM` 클래스는 아래와 같은 5개의 변수를 받습니다.

- data: 분석할 dataframe을 지정해 줍니다.
- depvar: 종속 변수(측정 결과)
- subject: 데이터 식별값
- within:  각각의 실험군 식별값 
- aggregate_func: 선택적 설정값으로 만약 측정 결과의 평균을 이용하려면 “mean”으로 설정해줍니다. 

## One-way AnovaRM

In [6]:
import pandas as pd

df = pd.read_csv('./data/rmAOV1way.csv')
df.groupby('cond').head()

    Sub_id           rt   cond
0        1   971.826563  noise
1        2   857.608167  noise
2        3  1035.354758  noise
3        4   867.620871  noise
4        5   928.381831  noise
60       1   703.502265  quiet
61       2   690.034816  quiet
62       3   559.329313  quiet
63       4   648.956331  quiet
64       5   760.869441  quiet

- Sub_id 행은 subject identifier
- rt 행은 dependent variable(종속 변수)
- cond 행은 independent variable(비종속 변수; 각각의 실험군을 식별하는 값)

으로 분석을 해보겠습니다.

In [8]:
from statsmodels.stats.anova import AnovaRM

aovrm = AnovaRM(df, 'rt', 'Sub_id', within=['cond'])
res = aovrm.fit()

print(res)

               Anova
===================================
     Num DF  Den DF F Value  Pr > F
-----------------------------------
cond 1.0000 59.0000 499.1549 0.0000
===================================


## Two-way AnovaRM

위의 예시와 다른것은 2개의 변수로 리스트가 구성되어 있다는 것입니다.

In [12]:
df2way = pd.read_csv('./data/rmAOV2way.csv')
df2way.groupby(['iv1','iv2']).head(3)

     Sub_id           rt    iv1     iv2
0         1  1082.986553  noise    down
1         2   938.799689  noise    down
2         3  1101.470970  noise    down
60        1   629.660479  quiet    down
61        2   375.325900  quiet    down
62        3   405.918049  quiet    down
120       1  1192.056165  noise      up
121       2  1107.276088  noise      up
122       3  1052.990288  noise      up
180       1   700.854765  quiet      up
181       2   680.263083  quiet      up
182       3   576.832215  quiet      up
240       1  1212.157531  noise  middle
241       2  1350.431851  noise  middle
242       3  1336.930557  noise  middle
300       1   802.494859  quiet  middle
301       2   837.362776  quiet  middle
302       3   696.269005  quiet  middle

In [13]:
aovrm2way = AnovaRM(df2way, 'rt', 'Sub_id', within=['iv1', 'iv2'])
res2way = aovrm2way.fit()

print(res2way)

                 Anova
========================================
        Num DF  Den DF   F Value  Pr > F
----------------------------------------
iv1     1.0000  59.0000 2207.0162 0.0000
iv2     2.0000 118.0000  275.4144 0.0000
iv1:iv2 2.0000 118.0000    1.8651 0.1594
========================================